// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: LilyGo_T-Panel_Starter

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_StatusMessage = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_StatusMessage, lv_pct(92));
lv_obj_set_height( ui_StatusMessage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_StatusMessage, 0 );
lv_obj_set_y( ui_StatusMessage, -25 );
lv_obj_set_align( ui_StatusMessage, LV_ALIGN_BOTTOM_MID );
lv_label_set_long_mode(ui_StatusMessage,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_StatusMessage,"Studio Touch Display");
lv_obj_set_style_text_color(ui_StatusMessage, lv_color_hex(0xDEDEDE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_StatusMessage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_StatusMessage, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_StatusMessage, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelVersion = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelVersion, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelVersion, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelVersion, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_LabelVersion,"Version n");
lv_obj_set_style_text_color(ui_LabelVersion, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelVersion, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_LabelVersion, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_LabelVersion, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_LabelVersion, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_LabelVersion, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container1 = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, lv_pct(100));
lv_obj_set_height( ui_Container1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Container1, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_Container1,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Container1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelTime = lv_obj_create(ui_Container1);
lv_obj_set_height( ui_PanelTime, 80);
lv_obj_set_width( ui_PanelTime, lv_pct(91));
lv_obj_set_y( ui_PanelTime, 300 );
lv_obj_set_x( ui_PanelTime, lv_pct(0) );
lv_obj_clear_flag( ui_PanelTime, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelTime, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PanelTime, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelTime, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelTime, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelTime, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelTime, lv_color_hex(0x006E96), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_PanelTime, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_ValueTime = lv_label_create(ui_PanelTime);
lv_obj_set_width( ui_ValueTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ValueTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ValueTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_ValueTime,"HH:MM");
lv_obj_set_style_text_font(ui_ValueTime, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelCo2 = lv_obj_create(ui_Container1);
lv_obj_set_width( ui_PanelCo2, 210);
lv_obj_set_height( ui_PanelCo2, 80);
lv_obj_clear_flag( ui_PanelCo2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_PanelCo2, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelCo2, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelCo2, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelCo2, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelCo2, lv_color_hex(0x634F24), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_PanelCo2, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelPanel1 = lv_label_create(ui_PanelCo2);
lv_obj_set_width( ui_LabelPanel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanel1, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_LabelPanel1,"Co2");
lv_obj_set_style_text_align(ui_LabelPanel1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanel1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ValueCo2 = lv_label_create(ui_PanelCo2);
lv_obj_set_width( ui_ValueCo2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ValueCo2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ValueCo2, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_ValueCo2,"000");
lv_obj_set_style_text_font(ui_ValueCo2, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelHumidity = lv_obj_create(ui_Container1);
lv_obj_set_width( ui_PanelHumidity, 210);
lv_obj_set_height( ui_PanelHumidity, 80);
lv_obj_set_align( ui_PanelHumidity, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_PanelHumidity, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_PanelHumidity, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelHumidity, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelHumidity, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelHumidity, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanel2 = lv_label_create(ui_PanelHumidity);
lv_obj_set_width( ui_LabelPanel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanel2, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_LabelPanel2,"Humidity");
lv_obj_set_style_text_align(ui_LabelPanel2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanel2, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ValueHumidity = lv_label_create(ui_PanelHumidity);
lv_obj_set_width( ui_ValueHumidity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ValueHumidity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ValueHumidity, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_ValueHumidity,"00%");
lv_obj_set_style_text_font(ui_ValueHumidity, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelPolestar = lv_obj_create(ui_Container1);
lv_obj_set_width( ui_PanelPolestar, 210);
lv_obj_set_height( ui_PanelPolestar, 80);
lv_obj_set_y( ui_PanelPolestar, 200 );
lv_obj_set_x( ui_PanelPolestar, lv_pct(0) );
lv_obj_set_align( ui_PanelPolestar, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_PanelPolestar, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_PanelPolestar, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelPolestar, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelPolestar, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelPolestar, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanel6 = lv_label_create(ui_PanelPolestar);
lv_obj_set_width( ui_LabelPanel6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanel6, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_LabelPanel6,"Polestar");
lv_obj_set_style_text_align(ui_LabelPanel6, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanel6, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ValuePolestarBattery = lv_label_create(ui_PanelPolestar);
lv_obj_set_width( ui_ValuePolestarBattery, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ValuePolestarBattery, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ValuePolestarBattery, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_ValuePolestarBattery,"00%");
lv_obj_set_style_text_font(ui_ValuePolestarBattery, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BarPolestarBattery = lv_bar_create(ui_PanelPolestar);
lv_bar_set_value(ui_BarPolestarBattery,80,LV_ANIM_OFF);
lv_bar_set_start_value(ui_BarPolestarBattery, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BarPolestarBattery, lv_pct(100));
lv_obj_set_height( ui_BarPolestarBattery, lv_pct(50));
lv_obj_set_align( ui_BarPolestarBattery, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_set_style_bg_color(ui_BarPolestarBattery, lv_color_hex(0x664C10), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BarPolestarBattery, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BarPolestarBattery, lv_color_hex(0x664C10), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_BarPolestarBattery, 255, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_set_style_bg_color(ui_BarPolestarBattery, lv_color_hex(0xBF8E1C), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BarPolestarBattery, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BarPolestarBattery, lv_color_hex(0xAA0202), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_BarPolestarBattery, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_SpinnerPolestarCharging = lv_spinner_create(ui_PanelPolestar,1000,90);
lv_obj_set_width( ui_SpinnerPolestarCharging, 20);
lv_obj_set_height( ui_SpinnerPolestarCharging, 20);
lv_obj_set_x( ui_SpinnerPolestarCharging, 13 );
lv_obj_set_y( ui_SpinnerPolestarCharging, -22 );
lv_obj_set_align( ui_SpinnerPolestarCharging, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SpinnerPolestarCharging, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_bg_grad_dir(ui_SpinnerPolestarCharging, LV_GRAD_DIR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_SpinnerPolestarCharging, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_SpinnerPolestarCharging, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_SpinnerPolestarCharging, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SpinnerPolestarCharging, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_SpinnerPolestarCharging, 255, LV_PART_MAIN| LV_STATE_DISABLED);

lv_obj_set_style_arc_color(ui_SpinnerPolestarCharging, lv_color_hex(0xF6A31B), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_SpinnerPolestarCharging, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_SpinnerPolestarCharging, 3, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_SpinnerPolestarCharging, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DISABLED );
lv_obj_set_style_arc_opa(ui_SpinnerPolestarCharging, 255, LV_PART_INDICATOR| LV_STATE_DISABLED);

ui_PanelVMC = lv_obj_create(ui_Container1);
lv_obj_set_width( ui_PanelVMC, 210);
lv_obj_set_height( ui_PanelVMC, 80);
lv_obj_set_y( ui_PanelVMC, 300 );
lv_obj_set_x( ui_PanelVMC, lv_pct(0) );
lv_obj_set_align( ui_PanelVMC, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_PanelVMC, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_PanelVMC, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelVMC, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelVMC, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelVMC, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanel8 = lv_label_create(ui_PanelVMC);
lv_obj_set_width( ui_LabelPanel8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanel8, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_LabelPanel8,"VMC");
lv_obj_set_style_text_align(ui_LabelPanel8, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanel8, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ValueVMC = lv_label_create(ui_PanelVMC);
lv_obj_set_width( ui_ValueVMC, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ValueVMC, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ValueVMC, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_ValueVMC,"Speed n");
lv_obj_set_style_text_font(ui_ValueVMC, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button1 = lv_btn_create(ui_PanelVMC);
lv_obj_set_width( ui_Button1, lv_pct(48));
lv_obj_set_height( ui_Button1, lv_pct(50));
lv_obj_set_align( ui_Button1, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x5A5770), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Button1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Speed 1");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xDEDEDE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button3 = lv_btn_create(ui_PanelVMC);
lv_obj_set_width( ui_Button3, lv_pct(48));
lv_obj_set_height( ui_Button3, lv_pct(50));
lv_obj_set_align( ui_Button3, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x5A5770), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Button3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Button3);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Night");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xDEDEDE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelConnections = lv_obj_create(ui_Container1);
lv_obj_set_height( ui_PanelConnections, 80);
lv_obj_set_width( ui_PanelConnections, lv_pct(91));
lv_obj_set_y( ui_PanelConnections, 322 );
lv_obj_set_x( ui_PanelConnections, lv_pct(24) );
lv_obj_set_align( ui_PanelConnections, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_PanelConnections,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PanelConnections, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_add_state( ui_PanelConnections, LV_STATE_CHECKED );     /// States
lv_obj_clear_flag( ui_PanelConnections, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_PanelConnections, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelConnections, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelConnections, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelConnections, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_PanelConnections, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_PanelConnections, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelConnections, lv_color_hex(0xAC0000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_PanelConnections, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_width(ui_PanelConnections, 2, LV_PART_MAIN| LV_STATE_CHECKED);

ui_CheckInternet = lv_checkbox_create(ui_PanelConnections);
lv_checkbox_set_text(ui_CheckInternet,"Internet");
lv_obj_set_width( ui_CheckInternet, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CheckInternet, LV_SIZE_CONTENT);   /// 1
lv_obj_add_state( ui_CheckInternet, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_CheckInternet, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CheckInternet, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE );    /// Flags
lv_obj_set_style_text_font(ui_CheckInternet, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_CheckInternet, lv_color_hex(0xAC0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CheckInternet, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_CheckInternet, lv_color_hex(0xAC0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_CheckInternet, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CheckInternet, lv_color_hex(0x43424A), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_CheckInternet, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_border_color(ui_CheckInternet, lv_color_hex(0x43424A), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_CheckInternet, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_CheckMQTT = lv_checkbox_create(ui_PanelConnections);
lv_checkbox_set_text(ui_CheckMQTT,"MQTT");
lv_obj_set_width( ui_CheckMQTT, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CheckMQTT, LV_SIZE_CONTENT);   /// 1
lv_obj_add_state( ui_CheckMQTT, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_CheckMQTT, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CheckMQTT, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE );    /// Flags
lv_obj_set_style_text_font(ui_CheckMQTT, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_CheckMQTT, lv_color_hex(0xAC0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CheckMQTT, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_CheckMQTT, lv_color_hex(0xAC0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_CheckMQTT, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CheckMQTT, lv_color_hex(0x43424A), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_CheckMQTT, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_border_color(ui_CheckMQTT, lv_color_hex(0x43424A), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_CheckMQTT, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_CheckHC2 = lv_checkbox_create(ui_PanelConnections);
lv_checkbox_set_text(ui_CheckHC2,"HC2");
lv_obj_set_width( ui_CheckHC2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CheckHC2, LV_SIZE_CONTENT);   /// 1
lv_obj_add_state( ui_CheckHC2, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_CheckHC2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CheckHC2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE );    /// Flags
lv_obj_set_style_text_font(ui_CheckHC2, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_CheckHC2, lv_color_hex(0xAC0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CheckHC2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_CheckHC2, lv_color_hex(0xAC0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_CheckHC2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CheckHC2, lv_color_hex(0x43424A), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_CheckHC2, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_border_color(ui_CheckHC2, lv_color_hex(0x43424A), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_CheckHC2, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_CheckHCL = lv_checkbox_create(ui_PanelConnections);
lv_checkbox_set_text(ui_CheckHCL,"HCL");
lv_obj_set_width( ui_CheckHCL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CheckHCL, LV_SIZE_CONTENT);   /// 1
lv_obj_add_state( ui_CheckHCL, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_CheckHCL, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CheckHCL, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE );    /// Flags
lv_obj_set_style_text_font(ui_CheckHCL, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_CheckHCL, lv_color_hex(0xAC0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CheckHCL, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_CheckHCL, lv_color_hex(0xAC0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_CheckHCL, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CheckHCL, lv_color_hex(0x43424A), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_CheckHCL, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_border_color(ui_CheckHCL, lv_color_hex(0x43424A), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_CheckHCL, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_PanelHA = lv_obj_create(ui_Container1);
lv_obj_set_width( ui_PanelHA, 210);
lv_obj_set_height( ui_PanelHA, 80);
lv_obj_set_y( ui_PanelHA, 100 );
lv_obj_set_x( ui_PanelHA, lv_pct(0) );
lv_obj_set_align( ui_PanelHA, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_PanelHA, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_PanelHA, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_PanelHA, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelHA, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelHA, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelHA, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelHA, lv_color_hex(0x8C0808), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_PanelHA, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelPanel4 = lv_label_create(ui_PanelHA);
lv_obj_set_width( ui_LabelPanel4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanel4, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_LabelPanel4,"HomeAssistant");
lv_obj_set_style_text_align(ui_LabelPanel4, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanel4, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ValueHA = lv_label_create(ui_PanelHA);
lv_obj_set_width( ui_ValueHA, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ValueHA, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ValueHA, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_ValueHA,"waiting");
lv_obj_set_style_text_font(ui_ValueHA, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelFibaro = lv_obj_create(ui_Container1);
lv_obj_set_width( ui_PanelFibaro, 210);
lv_obj_set_height( ui_PanelFibaro, 80);
lv_obj_set_y( ui_PanelFibaro, 200 );
lv_obj_set_x( ui_PanelFibaro, lv_pct(0) );
lv_obj_add_flag( ui_PanelFibaro, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_PanelFibaro, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_PanelFibaro, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelFibaro, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelFibaro, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelFibaro, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelFibaro, lv_color_hex(0x8C0808), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_PanelFibaro, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelPanel5 = lv_label_create(ui_PanelFibaro);
lv_obj_set_width( ui_LabelPanel5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanel5, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_LabelPanel5,"Fibaro");
lv_obj_set_style_text_align(ui_LabelPanel5, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanel5, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ValueFibaro = lv_label_create(ui_PanelFibaro);
lv_obj_set_width( ui_ValueFibaro, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ValueFibaro, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ValueFibaro, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_ValueFibaro,"waiting");
lv_obj_set_style_text_font(ui_ValueFibaro, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelInternet = lv_obj_create(ui_Container1);
lv_obj_set_width( ui_PanelInternet, 210);
lv_obj_set_height( ui_PanelInternet, 80);
lv_obj_set_y( ui_PanelInternet, 100 );
lv_obj_set_x( ui_PanelInternet, lv_pct(0) );
lv_obj_add_state( ui_PanelInternet, LV_STATE_FOCUSED );     /// States
lv_obj_add_flag( ui_PanelInternet, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_PanelInternet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_PanelInternet, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelInternet, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelInternet, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelInternet, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelInternet, lv_color_hex(0x8C0808), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_PanelInternet, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelPanel3 = lv_label_create(ui_PanelInternet);
lv_obj_set_width( ui_LabelPanel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanel3, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_LabelPanel3,"Internet");
lv_obj_set_style_text_align(ui_LabelPanel3, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPanel3, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ValueInternet = lv_label_create(ui_PanelInternet);
lv_obj_set_width( ui_ValueInternet, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ValueInternet, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ValueInternet, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_ValueInternet,"waiting");
lv_obj_set_style_text_font(ui_ValueInternet, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
