// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: LilyGo_T-Panel_Starter

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void anim_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_StatusMessage;
lv_obj_t *ui_LabelVersion;
lv_obj_t *ui_Container1;
lv_obj_t *ui_PanelTime;
lv_obj_t *ui_ValueTime;
lv_obj_t *ui_PanelCo2;
lv_obj_t *ui_LabelPanel1;
lv_obj_t *ui_ValueCo2;
lv_obj_t *ui_PanelHumidity;
lv_obj_t *ui_LabelPanel2;
lv_obj_t *ui_ValueHumidity;
lv_obj_t *ui_PanelPolestar;
lv_obj_t *ui_LabelPanel6;
lv_obj_t *ui_ValuePolestarBattery;
lv_obj_t *ui_BarPolestarBattery;
lv_obj_t *ui_SpinnerPolestarCharging;
lv_obj_t *ui_PanelVMC;
lv_obj_t *ui_LabelPanel8;
lv_obj_t *ui_ValueVMC;
void ui_event_Button1( lv_event_t * e);
lv_obj_t *ui_Button1;
lv_obj_t *ui_Label2;
void ui_event_Button3( lv_event_t * e);
lv_obj_t *ui_Button3;
lv_obj_t *ui_Label1;
lv_obj_t *ui_PanelConnections;
lv_obj_t *ui_CheckInternet;
lv_obj_t *ui_CheckMQTT;
lv_obj_t *ui_CheckHC2;
lv_obj_t *ui_CheckHCL;
lv_obj_t *ui_PanelHA;
lv_obj_t *ui_LabelPanel4;
lv_obj_t *ui_ValueHA;
lv_obj_t *ui_PanelFibaro;
lv_obj_t *ui_LabelPanel5;
lv_obj_t *ui_ValueFibaro;
lv_obj_t *ui_PanelInternet;
lv_obj_t *ui_LabelPanel3;
lv_obj_t *ui_ValueInternet;
// CUSTOM VARIABLES


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2( lv_event_t * e);
lv_obj_t *ui_Screen2;
lv_obj_t *ui_ValueMessage;
lv_obj_t *ui_Label3;
// CUSTOM VARIABLES


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3( lv_event_t * e);
lv_obj_t *ui_Screen3;
void ui_event_Button2( lv_event_t * e);
lv_obj_t *ui_Button2;
lv_obj_t *ui_Reboot;
lv_obj_t *ui_Label4;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void anim_Animation( lv_obj_t *TargetObject, int delay)
{

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_LONG_PRESSED) {
      _ui_screen_change( &ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_Screen3_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM  ) {
lv_indev_wait_release(lv_indev_get_act());
      refresh_scrollup( e );
}
}

void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      VMCButtonSpeed1( e );
}
}

void ui_event_Button3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      VMCButtonNight( e );
}
}

void ui_event_Screen2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_Screen1_screen_init);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
}
}

void ui_event_Screen3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
}
}

void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      RebootDevice( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui_Screen2_screen_init();
ui_Screen3_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
