// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: LilyGo_T-Panel_Starter

#ifndef _LILYGO_T_PANEL_STARTER_UI_H
#define _LILYGO_T_PANEL_STARTER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void anim_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_StatusMessage;
extern lv_obj_t *ui_LabelVersion;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_PanelTime;
extern lv_obj_t *ui_ValueTime;
extern lv_obj_t *ui_PanelCo2;
extern lv_obj_t *ui_LabelPanel1;
extern lv_obj_t *ui_ValueCo2;
extern lv_obj_t *ui_PanelHumidity;
extern lv_obj_t *ui_LabelPanel2;
extern lv_obj_t *ui_ValueHumidity;
extern lv_obj_t *ui_PanelPolestar;
extern lv_obj_t *ui_LabelPanel6;
extern lv_obj_t *ui_ValuePolestarBattery;
extern lv_obj_t *ui_BarPolestarBattery;
extern lv_obj_t *ui_SpinnerPolestarCharging;
extern lv_obj_t *ui_PanelVMC;
extern lv_obj_t *ui_LabelPanel8;
extern lv_obj_t *ui_ValueVMC;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label2;
void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_PanelConnections;
extern lv_obj_t *ui_CheckInternet;
extern lv_obj_t *ui_CheckMQTT;
extern lv_obj_t *ui_CheckHC2;
extern lv_obj_t *ui_CheckHCL;
extern lv_obj_t *ui_PanelHA;
extern lv_obj_t *ui_LabelPanel4;
extern lv_obj_t *ui_ValueHA;
extern lv_obj_t *ui_PanelFibaro;
extern lv_obj_t *ui_LabelPanel5;
extern lv_obj_t *ui_ValueFibaro;
extern lv_obj_t *ui_PanelInternet;
extern lv_obj_t *ui_LabelPanel3;
extern lv_obj_t *ui_ValueInternet;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2( lv_event_t * e);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_ValueMessage;
extern lv_obj_t *ui_Label3;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3( lv_event_t * e);
extern lv_obj_t *ui_Screen3;
void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Reboot;
extern lv_obj_t *ui_Label4;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
