// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: LilyGo_T-Panel_Starter

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void refresh_scrollup(lv_event_t * e);
void VMCButtonSpeed1(lv_event_t * e);
void VMCButtonNight(lv_event_t * e);
void RebootDevice(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
